# Generated by Django 2.2 on 2021-03-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20210309_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active_subscription',
            field=models.BooleanField(default=True),
        ),
    ]
