# Generated by Django 2.2 on 2021-03-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_customuser_active_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='active_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
